### ISSUE TITLE
[BUG] Broken links in wiki\QuickStart

### ISSUE THREAD

**Issue by alenros** [Jascen/TTS-PuzzleStrike#1]
All the links under Setup are broken.
I love Puzzle Strike and would love to help!

**Comment by Jascen** [comment]
Thanks for the report!

The links should be fixed now.

The wiki requires different paths when you edit+preview it vs when it’s posted. So hopefully I don’t make this mistake too often.

Regarding contributing/helping, I’m all for it! This was just a personal project that I built to play with family, but I’m hoping that other people enjoy it too.

The Tabletop Simulator workshop isn’t posted yet, but I hope to have it up in the next 48 hours.
